### ISSUE TITLE
center + offset

### ISSUE THREAD

**Issue by increpare** [increpare/zeedonk#164]
i tried to do

    Text.display(Text.CENTER,Text.CENTER+20,"press SPACE to start");

**Comment by increpare** [comment]
(maybe a bad idea, but thought I'd air the idea at least :P )

**Comment by TerryCavanagh** [comment]
Oh, right, that won't work - Text.CENTER is just a constant Int - something like -20000. When the display function sees that number, it centers the text. So what's happening is that it's been drawn at -19980, or something :P 

There is an alternative way to center text in TerryLib, but it's a bit weird. You can do this:

``` haxe
Text.display(Gfx.screenwidthmid, Gfx.screenheightmid, "Center me please", Col.WHITE, {align: Text.CENTER});
```
...yeah. Hmm. Any thoughts on a nicer way to do all this? Maybe having Text.align() as a seperate function that you call first, or something?

**Comment by increpare** [comment]
you could have it detect if the x/y coordinates are less than 19000 and if so draw them relative to the center coordinate (of -20000) or whatever  :P Tricksy, though.  Your approach is ok, though.

**Comment by TerryCavanagh** [comment]
Oh, of course! That's definitely something I can do. Ok, after I finish this example!
