### ISSUE TITLE
Figure out what's causing the "waiting for scriptfile" bug that people are reporting

### ISSUE THREAD

**Issue by TerryCavanagh** [increpare/zeedonk#167]
This also happened in my browser after loading Clone Avoid - however, after refreshing the page, it loaded normally.

My current theory:

So there's this callback function Webbridge.runscript() on the terrylib side which loads the script file after it's been called from the javascript side. If this is called before the terrylib side has fully loaded, then nothing will happen in the terrylib side. If that's what's causing it, the answer is to have the terrylib side call a "ready" function on the javascript side, to tell it that it's ready to be asked to load script files.

**Comment by increpare** [comment]
here's the callstack:

Uncaught TypeError: Cannot read property 'charCodeAt' of null
haxe_xml_Parser.doParse @       webthing.js:7634
haxe_xml_Parser.parse   @       webthing.js:7622
Xml.parse       @       webthing.js:3796
terrylib_util_Fontfile  @       webthing.js:44445
terrylib_Text.addfont   @       webthing.js:42901
terrylib_Text.setfont   @       webthing.js:42876
Webscript.scriptfound   @       webthing.js:3777
Webscript.loadscript    @       webthing.js:3725
Webbridge.runScript     @       webthing.js:2348
terryRun        @       (index):289
githubHTTPClient.onreadystatechange     @       (index):315

**Comment by increpare** [comment]
might as well reopen it until it's been verified fixed... :(

**Comment by increpare** [comment]
from lucas:

[Error] TypeError: null is not an object (evaluating 'buffer.__srcContext.getImageData')
	createImageData (webthing.js, line 15561)
	getPixel (webthing.js, line 15605)
	getPixel (webthing.js, line 13794)
	getPixel (webthing.js, line 29695)
	Fontfile (webthing.js, line 43500)
	addfont (webthing.js, line 41866)
	setfont (webthing.js, line 41823)
	addedtostage (webthing.js, line 1316)
	f (webthing.js, line 43552)
	__dispatchEvent (webthing.js, line 277)
	__dispatchEvent (webthing.js, line 434)
	__setStageReference (webthing.js, line 1201)
	addChild (webthing.js, line 881)
	init (webthing.js, line 1307)
	Core (webthing.js, line 1295)
	Load (webthing.js, line 1405)
	DocumentClass (webthing.js, line 1415)
	createInstance (webthing.js, line 3303)
	start (webthing.js, line 145)
	init (webthing.js, line 125)
	start (webthing.js, line 12003)
	display_onComplete (webthing.js, line 31523)
	f (webthing.js, line 43552)
	__dispatchEvent (webthing.js, line 277)
	__dispatchEvent (webthing.js, line 434)
	dispatchEvent (webthing.js, line 210)
	onLoaded (webthing.js, line 2812)
	start (webthing.js, line 31512)
	image_onLoad (webthing.js, line 12018)
	f (webthing.js, line 43552)
