### ISSUE TITLE
TickyTacky style game chaining?

### ISSUE THREAD

**Issue by TerryCavanagh** [increpare/zeedonk#175]
Wouldn't be too hard to do, and could lead to some cool things

**Comment by increpare** [comment]
I'm not a big fan of chain games - it's not a style of game design I
personally enjoy (either the development side or the playing side), and I
wouldn't particularly want to encourage it - if you're putting something in
here, given how limited it is, you're also suggesting it's a good idea.
I'm happy to leave the call to you, though.

S

**Comment by TerryCavanagh** [comment]
Ok, cool - this seems like part of a larger issue of scene control to me, so let's leave it till you're back in london and talk about it then.
