### ISSUE TITLE
Firefox framerate starts pretty good, but after running in the editor for 5+ minutes gets pretty slow

### ISSUE THREAD

**Issue by TerryCavanagh** [increpare/zeedonk#181]
This is becoming a pretty reliable thing, we should look into it

**Comment by increpare** [comment]
Don't seem to be able to repro it here.  For the record, here are the tools for probing it:

1 - the regular profiler
2 - type about:memory into the url bar (in a fresh tab) to get to the memory stats page, which will tell you what's allocating what, in case there's a memory leak.

**Comment by increpare** [comment]
did profiling, seems to be calling set-interval a lot - 6/7 times per frame. that might be making things crazy 
(or it might be meaningless. it's not like they're taking up most of the time or anything, but there are sure a lot of them)

on firefox, I'm getting many many simultaneous calls to setinterval - is this right?

<img width="917" alt="screen shot 2015-09-07 at 07 58 41" src="https://cloud.githubusercontent.com/assets/465632/9710865/69ab7d14-5536-11e5-9feb-6b3471f30183.png">

(it uses a different timer system in chrome, from what i can tell)

in general, it's using crazy cpu right from the start. are you getting this as well?

**Comment by increpare** [comment]
eventually the same seems to happen in chrome. haven't figured it out yet.

**Comment by TerryCavanagh** [comment]
Just added a line that might help!
```haxe
// start game loop
if(_timer != null) _timer.stop();
_timer = new Timer(tickrate);
_timer.run = ontimer;
```

**Comment by TerryCavanagh** [comment]
I think that fixed it, actually! Woo

**Comment by increpare** [comment]
:D :D
