### ISSUE TITLE
Name this project

### ISSUE THREAD

**Issue by TerryCavanagh** [increpare/zeedonk#195]
Still thinking about this. Names are the worst.

**Comment by increpare** [comment]
BORK BORK

**Comment by increpare** [comment]
BORK BORK ONLINE

**Comment by increpare** [comment]
choo

(and the standalone one, being more powerful, could be called choo choo)

**Comment by increpare** [comment]
cherrylib is good

**Comment by increpare** [comment]
HAXEGON 
ZEDONK
