### ISSUE TITLE
Write a ispixeltransparent(x, y) and setpixeltransparent(x, y)

### ISSUE THREAD

**Issue by TerryCavanagh** [increpare/zeedonk#239]
Have been trying to do this one for the last little while, and seem to have run into a weird bug in OpenFL. Filing an issue there.

**Comment by increpare** [comment]
name's a bit long - how about get/setpixelalpha?

**Comment by TerryCavanagh** [comment]
eh, ok :)

**Comment by increpare** [comment]
maybe transparent is a friendlier word, though!

**Comment by TerryCavanagh** [comment]
It looks like this has been fixed in the newest version of OpenFL! I'll tackle this when that arrives.

**Comment by TerryCavanagh** [comment]
It's arrived!

Decided to implement the functions with a special Col.TRANSPARENT constant. So, Gfx.setpixel(x, y, Col.TRANSPARENT), or if(Gfx.getpixel(x,y) == Col.TRANSPARENT).

**Comment by increpare** [comment]
sounds good :D
