### ISSUE TITLE
consistent mascot colors?

### ISSUE THREAD

**Issue by increpare** [increpare/zeedonk#272]
<img width="167" alt="screen shot 2015-09-17 at 11 32 09" src="https://cloud.githubusercontent.com/assets/465632/9931020/cfd0b2d4-5d2f-11e5-888a-357aeef57fe7.png">

<img width="177" alt="screen shot 2015-09-17 at 11 32 03" src="https://cloud.githubusercontent.com/assets/465632/9931021/d127f502-5d2f-11e5-9db1-a436df3ba70e.png">

<img width="459" alt="screen shot 2015-09-17 at 11 33 50" src="https://cloud.githubusercontent.com/assets/465632/9931055/0f214138-5d30-11e5-910d-a5a000924369.png">

i like the small grey one and the large brown one. i'm okay with them being inconsistent, but want your thoughts.

**Comment by TerryCavanagh** [comment]
I agree! Small gray and large brown are best!
