### ISSUE TITLE
waiting screen animals are blurry on safari

### ISSUE THREAD

**Issue by increpare** [increpare/zeedonk#320]
<img width="386" alt="screen shot 2015-09-20 at 12 12 09" src="https://cloud.githubusercontent.com/assets/465632/9980424/e93e4e08-5f90-11e5-95b5-1f575cdcd47f.png">

guess you gotta call webkitsmoothing again?

**Comment by TerryCavanagh** [comment]
Oh, I think I know what do to here!

**Comment by TerryCavanagh** [comment]
Did that fix it?

**Comment by increpare** [comment]
Nope.

I'd guess it's to do with the smoothing settings on the source (or maybe target) canvas (horse/field)

**Comment by TerryCavanagh** [comment]
Boo. This is complicated, then :/

**Comment by increpare** [comment]
one thing to try doing would be hacking the .js file with thingy thingy to see if that fixes it -

**Comment by TerryCavanagh** [comment]
Ok, I just did it pixel by pixel instead. This isn't meant to be a realtime thing anyway, so it's fine for now! Might speed it up later.
