### ISSUE TITLE
text.display - font position is different if you set a color sometimes?

### ISSUE THREAD

**Issue by increpare** [increpare/zeedonk#325]
Gfx.clearscreen(Col.BLUE);
    Text.setfont(Font.C64);
    var s = "How quickly daft 
    jumping zebras vex.";

    Text.display(5,Text.CENTER,s.toLowerCase());
    Text.display(5,Text.CENTER,s.toLowerCase(),Col.BLACK);

produces

<img width="351" alt="screen shot 2015-09-20 at 12 39 40" src="https://cloud.githubusercontent.com/assets/465632/9980519/adc92984-5f94-11e5-81bd-c05b5c5deb24.png">

**Comment by TerryCavanagh** [comment]
Really weird! Appears to be part of #307, mysteriously.

**Comment by increpare** [comment]
spooky shizzle
