### ISSUE TITLE
make a raycaster

### ISSUE THREAD

**Issue by increpare** [increpare/zeedonk#361]

**Comment by TerryCavanagh** [comment]
Ok! I had a go at this.

play.html?p=da8bed57397c332be740

Sadly, this basically just proves that Zeedonk isn't really cut out for this sorta thing - even untextured and low res, it's a struggle to keep at 30fps. So I'm gonna leave it at that, and focus on making examples that are less actiony and showcase what the engine *can* do well.

**Comment by TerryCavanagh** [comment]
Heh. Slightly updated version based on your splitscreen suggestion, which at least runs at 30fps: play.html?p=d6b99e6a55e82b3fad28
