### ISSUE TITLE
is there a way to copy a rectangle from one image to another?

### ISSUE THREAD

**Issue by increpare** [increpare/zeedonk#371]

**Comment by increpare** [comment]
other than by providing an intermediate wxh image? (which is satisfactory for my purposes)

**Comment by TerryCavanagh** [comment]
Oh, no, there isn't. :( Should we add it?

**Comment by increpare** [comment]
the standard flash blit way is to add extra w/h parameters to the end of grabimagefromimage
but, as I said, I could work around it, so it's not really necessary for now
