### ISSUE TITLE
Resizing sprite to a non-whole number creates grid lines on sprite

### ISSUE THREAD

**Issue by acidpoison** [increpare/zeedonk#396]
http://www.zeedonk.net/beta/play.html?p=73d149082432d60a8b30

**Comment by TerryCavanagh** [comment]
Ahh, good catch! This is a pretty easy fix, I think.

(though: since Zeedonk doesn't have antialiasing, it'll produce a pretty ugly result, with some pixels being scaled to 2x2 and others being 1x1. Ah well.)
