### ISSUE TITLE
i don't understand this error

### ISSUE THREAD

**Issue by increpare** [increpare/zeedonk#412]
Running Program
line 22 : RUNTIME ERROR
Unknown error type in line 22:
Error name: null
Javascript Stack:

---

    var fonts = [Font.C64, Font.COMIC, Font.DEFAULT, Font.DOS,Font.PRESSSTART,Font.RETROFUTURE];
    var curfonts = [];
    var colors = [];
    var heights = [];
    function genString(){
      var s="";
      var wordcount =Random.int(3,6);
      for (i in 0...wordcount){    
        s+=Random.pickstring("a","rose","by","any","other","name","would","smell","as","sweet")+" ";
      }
      return s;
    }

    var strings=[];
    var h = 15;
    function update(){

      if(Game.time%10==0){
        strings.push(genString());
        var font = curfonts[Random.int(0,fonts.length-1)];
        curfonts.push(font);
        Text.setfont(font);
        heights.push(Text.height());
        colors.push(Gfx.hsl(Random.int(0,359),1.0,0.5));

        var totalheight=0;
        for (i in 0...heights.length){
          totalheight+=heights[i];
        }

        if (totalheight>Gfx.screenheight) {
          strings.splice(0,1);
          curfonts.splice(0,1);
          colors.splice(0,1);
        }
      }
      for (i in 0...strings.length){
        Text.setfont(fonts[curfonts[i]],1);
        Text.display(0,i*h,strings[i],colors[i]);
      }
    }

**Comment by TerryCavanagh** [comment]
Fixed
