### ISSUE TITLE
still some weird text caching bugs

### ISSUE THREAD

**Issue by increpare** [increpare/zeedonk#60]
nothing reproducable, but right now in my current session when I try to print 0 it prints cat.

**Comment by TerryCavanagh** [comment]
I think this was fixed a while ago with this line:

''' haxe
public static function display(x:Float, y:Float, dytext:Dynamic, col:Int = 0xFFFFFF, ?parameters:Textdrawparams) {
	  var text:String = Convert.tostring(dytext);
'''

Feel free to reopen if I've missed something!
